### Numpy

In [ ]:
# Numpy
import numpy as np

# Can give list tuple , list ,set
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # Single Dimension Array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
# cannot reshape array of size 5 into shape (1,3)
#arr2.reshape(1,3)
arr2.reshape(1,5) #1 row 5 column
print(type(arr2)) 
print(arr2)

<class 'numpy.ndarray'>
[1 2 3 4 5]


#### Create directly- 2D Array

In [ ]:

arr2=np.array([[1,2,4],[3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 4]
 [3 4 5]]
(2, 3)


#### Creating using range

In [ ]:

arr3=np.array(range(0,10,2))
print(arr3)
print(arr3.reshape(1,5))
arr3=np.array(range(0,10,2))
print(arr3.reshape((5,1)))

[0 2 4 6 8]
[[0 2 4 6 8]]
[[0]
 [2]
 [4]
 [6]
 [8]]


#### Other methods

In [ ]:

#all ones
arr4=np.ones(9).reshape(3,3)
print(arr4)

# Other methods
#all zeros
arr4=np.zeros(9).reshape(3,3)
print(arr4)

# Other methods
#Identity Matrix
arr4=np.eye(3)
print(arr4)


## Attributes of numpy
print("Array ",arr4)
print("Shape ",arr4.shape)
print("number of dimension ",arr4.ndim)
print("Size ",arr4.size)
print("type of element ",arr4.dtype)
print("Item size in byte ",arr4.itemsize)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape  (3, 3)
number of dimension  2
Size  9
type of element  float64
Item size in byte  8


#### Numpy Vectorized operations

In [ ]:

arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,0,4])

#Element wise addition
print("Addition ", arr1+arr2)
#Element wise substraction
print("Addition " ,arr2+arr1)

#Element wise multiplications
print("Addition ", arr2*arr1)

#Element wise division
print("Addition ", arr2*arr1)

#Element wise modulo
print("Addition ", arr2%arr1)

Addition  [ 8 10 12  4  9]
Addition  [ 8 10 12  4  9]
Addition  [ 7 16 27  0 20]
Addition  [ 7 16 27  0 20]
Addition  [0 0 0 0 4]


#### Universal Functions

In [ ]:


arr=np.array([1,2,3,4,5])

#Square element
print(np.sqrt(arr))
#sine element
print(np.sin(arr))
#cube element
print(np.exp(arr))
#log element
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


#### Slicing and indexing

In [ ]:

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)
#retrive 0th row 2nd column
arr[0][2]

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(3)

#### Slicing -getting 7 8 11 12

In [ ]:

print(arr[1:]) #Taking all from first row
print(arr[1:,2:]) #Taking all from first row and second column
#getting 3 4 7 8 
print(arr[0:2,2:])
#getting 6 7 10 11
print(arr[1:,1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


#### Modify Array Element

In [ ]:

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0,0]=100
print(arr)

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[1:,]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Statical Concept -- normalization

In [ ]:

data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


#### Statical Concept -- normalization

In [ ]:

data=np.array([1,2,3,4,5])
print(np.mean(data))
print(np.std(data))
print(np.median(data))
print(np.var(data))#vairance


3.0
1.4142135623730951
3.0
2.0


#### Logical Operation

In [ ]:

data=np.array([1,2,3,4,5,7,8,9,10])
print(data<5)
print(data[data<5])
print(data[(data<5) & (data>1)])


[ True  True  True  True False False False False False]
[1 2 3 4]
[2 3 4]
